[package]
name = "ledger-device-base"
version = "0.1.0"
edition = "2021"

[dependencies]
serde = { version = "1", features = ["derive"] }
thiserror = "2.0.16"
async-trait = "0.1"
ledger-transport = { path = "../ledger-transport" }
